= Analyze Tracking Logic for Lost and Found Items #33
== Research objectives
This research aims to identify and analyze how existing digital Lost and Found platforms manage reported items throughout their lifecycle. Based on observed tracking mechanisms,  the research identifies common item states and workflows. Using these findings, it proposes  a recommended tracking logic and set of item states for our project.

== Analysis of Existing Digital Lost and Found  Platforms

=== A) What tracking logic other Lost and Found Websites use to manage Found or Lost items?
After reviewing  some lost and found websites,I identified common  patterns in how to identify items.

[NOTE]
====
 Keep in mind that some  of these observations  are  based on assumptions and some kind of reverse engineering, since internal workflows are not publicly Available. 
====
I am going to use **bold**, to identify what are  my assumptions

==== 1. SJU Lost and Found:
Based on the platforms structure, the tracking logic appears to follow this flow:

1.#Item Report Submission:#
* First, their  website has an established Lost items report template. After a user fills the report 
**The item is classified/ reported as “Lost”.**


2.#Clain number Generation#
Once the Lost item is reported, the platform sends the user a “claim number” to track the  item. 
[NOTE]
====
 Note: The website also allows users to edit or check their lost items status. 
====
Once the report is done it is reviewed and a search is conducted to find a potential match on the database. 
**For this step I’m going to assume the item passes through a “In progress/Search” status.**


3.#Matching Process# 
If the item is found(a match) they send an email to notify the user and they are guided on how to retrieve the item. 
**The item goes from a searching/In progress status to a “Found” status.**


4.#Ownership confirmation and retrieval#
Once the item is retrieved by the owner it goes to a  **Claimed/Retrieved Status**

5.#Case closure#
The case then is closed
**Report is closed/archived**

==== DeliverBack Website:
1.Guess report that they left an item behind
**Item reported as “Lost”**


2.Worker confirms that they found the item by clicking a button
**Item reported as “Found”**

3.Ship the item back to the owner
**The item is “Claimed/Confirmed”, then its state changes to “In process” and when the client confirms the shipment of their item, item status changes as "Received" and then  finally it is “Archived”. With this I assume the confirmation of the client ends the lifecycle.**
[NOTE]
====
In process represents shipment and handling
====

=== B) Commonly used item states?
The most commonly used status indicators/item states for  Lost/Found items include:
- Claimed
- Matched
- Reported Lost
- Reported Found
- Unclaimed
- In progress/Searching

=== C) Recommended Tracking Logic for our project/platform

Based on the research, I think, we could  Implement  some of the following “tags”/ lifecycles to track the status of reported lost items with primarily and secondary states :

=== Primary State:
All items would initially be categorized as either:

*Lost:* When an owner reports their item as lost
or
*Found:* When an item is reported as found, but there is no owner claiming it

=== Secondary State:
(This state is mostly  for Found items)
Items can obtain extra tags based on: 
*Not Claimed :* For an item reported lost but that nobody has claimed

*Found item/Matched:* An item reported as Lost that  has been found 

*Claimed:* For an item that has been  reported as Found  and it has already been verified the ownership of the item

*Searching:* when the system is attempting to match the item

*In process:* When the owner confirms that they are going to retrieve the item

*Retrieved:* When the owner retrieves the item

*Archived/Deleted:* Once the item is found we can archive it or delete it

*Pending Ownership:* When the Lost item is matched with a found item on the database and we are waiting for the owner confirmation and ownership verification

[NOTE]
====
if after a long period of time the item is never found, the item may be archived
====


**Recommended Feature:**
*-Check Status:* Users are going to get real time notifications of the status of their report, but I think they also could check the status of their report on the platform


=== Recommended  ownership verification for retrieval process

Once ownership is verified, the system could generate a random 5-7 digit code. This code is unique and only accessible to the verified owner. 
During pickup the owner provides the code to the person holding the item. Then the code is entered to the platform. Once verified, the item status automatically changes to “Retrieved” and lastly the case is moved to the “Archived” stage.

=== Lost and Found Item Stages Scenarios:

#Claiming a Lost item:#
If the owner  claims an item reported as **“Found”** state  and verifies  ownership , the item becomes **“Claimed”** state. Once the user confirms he is going to retrieve the item, the item goes to **“Claimed/In process” ** state.  Using the recommendation above: The owner could receive a unique confirmation retrieval code, which they submit to the person or location returning the lost item. Once the owner meets the person or goes to the designated safe point to retrieve the item, they provide  the code to confirm ownership  and complete the retrieval process. Once the code is submitted on the platform, the item status becomes "Retrieved" and finally the item is“Archived or Deleted”.

#Matching Lost and Found items#
 If our system matches a “Lost” item with a  **“Found item”**  in our database, the owner receives a notification that their item has been found. The item is **“Matched”.** And goes to **“Pending ownership” ** status. They can confirm that the item is theirs and verified ownership. Item status changes to  **“Claimed”.** Once the owner confirms that they are going  to pick up the item,  the item status becomes **“Claimed”** and **“In process”. **
[NOTE]
====
While the owner could manually mark the item as retrieved, we could also use the verification code to ensure the item is properly returned. 
====
Once the confirmation code/or confirmation of retrieval is submitted, automatically the item status changes to **“Retrieved”**, and after a few hours or immediately if there are no issues, the item is **“Archived/Deleted”.**

#Reporting a Found Item#
**If** a **“Lost”** item is reported as **"Found”** by another user the item goes through the same process as described above.

#Found item Not Claimed#
**If** a **"Found”** item is still not claimed, the item status is “Not claimed” until someone claims it. Once claimed the same retrieval process described above applies. However, if a “Found” item remains unclaimed for a very looong period of time (a year or so) the team can decide whether to keep the item on the platform or to **“Archive/Delete”**

#Reported Lost item is never found#
**If** a **“Lost”** item is not found the owner can **“Check Status”** and edit their lost item report if they want to add more information. After a long period of time, we as a team can determine if the item will still be part of the platform or if the item status is going to be **“Archived or Deleted”.**

 

=== For this project, is it better an app or a website?
Personally, considering the nature of our project, I think a website is a more suitable option than a mobile application. Because Lost and Found situations are rather occasional/not that frequent, meaning that most people would not be motivated to install a dedicated app on their devices. Unless someone regularly loses objects or frequently finds lost items, otherwise the app would likely remain unused. A website on the other hand can be accessed whenever it is needed, without requiring installation. 




=== References

Lost and Found SJU, [Online] Available: https://sju.lostandfoundsite.net/

DeliverBack, [Online] Available: https://deliverback.com/


